### ISSUE TITLE
FluidPlug fails to run with 'no lv2_lib_descriptor' error

### ISSUE THREAD

**Issue by asbaklm** [falkTX/FluidPlug#1]
I tried installing FluidPlug from git, https://github.com/falkTX/FluidPlug

It compiled and installed fine but when trying to use it, it throws "no lv2_lib_descriptor" errors. Anybody have any idea about this?

lilv_lib_open(): error: No `lv2_descriptor' or`lv2_lib_descriptor' in /usr/lib/lv2/AirFont320.lv2/FluidPlug.so
createSynthInstance: synthi class:FluidPlug label:AirFont320 LV2 can not be created
lilv_lib_open(): error: No `lv2_descriptor' or`lv2_lib_descriptor' in /usr/lib/lv2/FluidGM.lv2/FluidPlug.so
createSynthInstance: synthi class:FluidPlug label:FluidGM LV2 can not be created

**Comment by asbaklm** [comment]
Updating LV2 from drobilla seems to have helped, it was recompiled and now loads in Carla.

**Comment by falkTX** [comment]
Sorry I missed this bug report.
The reason for the missing symbols is because the build hides all but the ones marked to export.
Old LV2 headers were missing the proper export define.
So updating LV2 headers fixes it.
