### ISSUE TITLE
wget error 403

### ISSUE THREAD

**Issue by mrwsl** [falkTX/FluidPlug#12]
When I try to build the plugins with `make` I get `403` http errors. I don't know why wget (`GNU Wget 1.21.3`) is not following the redirects, but the fix is rather simple: replace the `http` with `https` in the `Makefile`. I would have created a PR, but GitHub is throwing errors at me at the moment.

**Comment by Gimmeapill** [comment]
Error confirmed here as well, but disabling https is not a solution....

**Comment by mrwsl** [comment]
I didn't disable https but changed the URLs in the `Makefile` to https.

**Comment by mrwsl** [comment]
Closed by #13.
