### ISSUE TITLE
Custom GUI missing when cross building with YOCTO

### ISSUE THREAD

**Issue by schnitzeltony** [falkTX/FluidPlug#3]
I have cross-build fluidplugins for RaspberryPi 3 with YOCTO environment. Plugins can be loaded and played with ardour5 and qtractor. When I open plugin's GUI from both applications I get only the standard/fallback dialogs where I can set select sound and modify the level. Looking at the sources I see the modgui stuff and would expect some customized GUI for FluidPlugins.
This is not necessarily a bug in FludPlug but I think my build is missing something that modgui is ignored. Some pointers?

**Comment by falkTX** [comment]
This is expected.
Those are not plugin UIs, but something only done for MOD.
There will be no native UIs since the plugins are quite simple and don't need them at all.

**Comment by schnitzeltony** [comment]
1. So I am doing it right - thanks for clarification
2. Out of curiosity: What do you mean by MOD

**Comment by falkTX** [comment]
Yes, you're doing nothing wrong. you should not expect to have desktop UIs for these plugins.

By MOD I mean this https://moddevices.com/
Those "guis" are small html files used on the web interface. See http://wiki.moddevices.com/wiki/Chapter_2:_Web_interface
