### ISSUE TITLE
Please remove 'sse' flags in makefiles, because sse isn't used in this project

### ISSUE THREAD

**Issue by yurivict** [falkTX/FluidPlug#5]
```
Makefile.mk:BASE_OPTS  = -O2 -ffast-math -mtune=generic -msse -msse2 -mfpmath=sse -fdata-sections -ffunction-sections
Makefile.mk:BASE_FLAGS += -msse -msse2
```

```sse``` flags break build on non-Intel/AMD platforms.

**Comment by falkTX** [comment]
On intel platforms (which is the most common case) we need those flags in audio plugins for performance reasons.
For non-intel platforms, just do `make NOOPT=true` as it is typical with my makefiles.
These plugins are building for MOD Duo, which uses an ARM board, without issues.
